language: php

sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script :
  - phpenv config-rm xdebug.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpcs --standard=PSR2 src
  - bin/phpunit --coverage-text -c app