language: php

php:
  - 5.6
  - hhvm
  - 7.0

before_script :
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - bin/phpcs --standard=PSR2 src
  - bin/phpunit --coverage-text -c app