language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

before_script :
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update && composer --version
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpcs --standard=PSR2 src
  - bin/phpunit --coverage-text -c app