language: php

sudo: false

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_script :
  - phpenv config-rm xdebug.ini
  - composer self-update && composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpcs --standard=PSR2 src
  - bin/phpunit --coverage-text -c app