language: php

php:
  - 5.6
  - hhvm
  - 7.0

before_script :
  - composer self-update
  - composer install
  - chmod -R 777 app/cache app/logs

script:
  - bin/phpcs --standard=PSR2 src
  - phpunit -c app