app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_routing:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routing.yml"