app_product_v1:
    resource: app.controller.product
    type:   rest
    prefix:   /v1
    name_prefix:  api_v1_

app_category_v1:
    resource: app.controller.category
    type:   rest
    prefix:   /v1
    name_prefix:  api_v1_