services:
    util.inflector:
      class: AppBundle\Util\Inflector\NoPluralize

    app.request.normalize.sort:
      class: AppBundle\Application\Normalizer\NormalizeSort
      public: false

    app.request.normalize:
      class: AppBundle\Application\Normalizer\RequestNormalizer
      arguments: ['@app.request.normalize.sort']

    app.fos_rest.view.view:
        class: FOS\RestBundle\View\View
        factory: [FOS\RestBundle\View\View, create]

    app.rest.base:
      class: AppBundle\Application\Rest\v1\RestBase
      arguments: ['@doctrine.orm.entity_manager','@app.fos_rest.view.view','@app.request.normalize','@form.factory']