AppBundle\Entity\Product:
    exclusion_policy: all
    properties:
        id:
            type: integer
        name:
            type: string
        description:
            type: string
        active:
            type: boolean