AppBundle\Entity\Category:
    exclusion_policy: all
    properties:
        id:
            type: integer
            groups: [Default]
        name:
            type: string
            groups: [Default]
        description:
            type: string
            groups: [Default]